mysql:
    host: "127.0.0.1"
    database: qianka
    user: root
    password: '123456'
    time_zone: "+8:00"

redis:
    host: "127.0.0.1"
    port: 6379

tornado:
    debug: True
    autoreload: True
        
duiba:
    appKey: "yuiyiuhyuiohou"
    appSecret: "g96bgb6tGvuohoijUzwsw9JoqjSttLhd3"
